name: Security Code Analysis

on:
  push:
    branches:
      - main
      - develop
      
jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SecurityCodeScan
        uses: security-code-scan/security-code-scan-results-action@v1.3